# Generated by Django 3.1.3 on 2020-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliders',
            options={'verbose_name_plural': 'sliderler'},
        ),
        migrations.AddField(
            model_name='sliders',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim seçiniz'),
        ),
    ]
