# Generated by Django 3.1.3 on 2020-11-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_sliders_slugedtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('lastname', models.CharField(max_length=100, verbose_name='soyad')),
                ('telephone', models.CharField(max_length=100, verbose_name='telefon')),
                ('email', models.EmailField(max_length=100, verbose_name='eposta')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('price', models.IntegerField(max_length=100, verbose_name='fiyat')),
                ('currency', models.CharField(choices=[('tl', 'TL'), ('usd', 'USD'), ('euro', 'EURO')], default='tl', max_length=5, verbose_name='kur')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim seçiniz')),
                ('status', models.BooleanField(default=True, verbose_name='gösterilsin mi?')),
                ('designedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.designer')),
            ],
        ),
    ]
