# Generated by Django 3.1.3 on 2020-11-30 19:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_designer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=3, null=True, verbose_name='cinsiyet'),
        ),
        migrations.AddField(
            model_name='product',
            name='inDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoesSize',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], max_length=26, null=True, verbose_name='ayakkabı numarası'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl')], max_length=20, null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='designedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.designer', verbose_name='tasarımcı'),
        ),
    ]
