# Generated by Django 3.1.3 on 2020-11-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201130_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name_plural': 'TaSaRıMCı'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Ürünler'},
        ),
    ]
