# Generated by Django 3.1.3 on 2020-12-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201201_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='designedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.designer', verbose_name='tasarımcı'),
        ),
    ]
