# Generated by Django 3.1.3 on 2020-12-01 20:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201201_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=3, null=True, verbose_name='kategoriler'),
        ),
        migrations.DeleteModel(
            name='CategoryTag',
        ),
    ]
