# Generated by Django 3.1.3 on 2020-12-01 20:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20201201_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kadin', 'kadin'), ('erkek', 'erkek'), ('elektronik', 'elektronik'), ('sport', 'sport'), ('aksesuar', 'aksesuar'), ('makyaj', 'makyaj')], max_length=44, null=True, verbose_name='kategoriler'),
        ),
    ]
