# Generated by Django 3.1.3 on 2020-12-02 08:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20201201_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('red', 'red'), ('pink', 'pink'), ('orange', 'orange'), ('yellow', 'yellow'), ('purple', 'purple'), ('green', 'green'), ('blue', 'blue'), ('brown', 'brown'), ('black', 'black')], max_length=52, null=True, verbose_name='renk'),
        ),
    ]
