# Generated by Django 3.1.4 on 2020-12-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='EPOSTA')),
                ('sosyal', models.CharField(blank=True, max_length=100, null=True, verbose_name='SosyalAddress')),
                ('massage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
