# Generated by Django 3.1.4 on 2020-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='sosyal',
            field=models.URLField(blank=True, null=True, verbose_name='SosyalAddress'),
        ),
    ]
