# Generated by Django 3.1.4 on 2020-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20201206_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='sosyal',
        ),
        migrations.AddField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='footer',
            name='googlePlus',
            field=models.URLField(blank=True, null=True, verbose_name='googlePlus'),
        ),
        migrations.AddField(
            model_name='footer',
            name='pinterest',
            field=models.URLField(blank=True, null=True, verbose_name='pinterest'),
        ),
        migrations.AddField(
            model_name='footer',
            name='tumblr',
            field=models.URLField(blank=True, null=True, verbose_name='tumblr'),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='footer',
            name='vimeo',
            field=models.URLField(blank=True, null=True, verbose_name='vimeo'),
        ),
    ]
