# Generated by Django 3.1.4 on 2020-12-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20201207_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seyirci',
            new_name='Contacts',
        ),
    ]
