# Generated by Django 3.1.4 on 2020-12-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20201207_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Seyirci',
        ),
        migrations.AlterModelOptions(
            name='seyirci',
            options={},
        ),
    ]
