# Generated by Django 3.1.4 on 2020-12-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20201207_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='seyirci',
            name='countrylocation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
