# Generated by Django 3.1.4 on 2020-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_seyirci_countrylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='seyirci',
            name='konum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
