# Generated by Django 3.1.4 on 2020-12-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_seyirci_konum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seyirci',
            name='konum',
        ),
    ]
