# Generated by Django 3.1.4 on 2020-12-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20201208_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='markname',
            new_name='brandsname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='markpic',
        ),
        migrations.AddField(
            model_name='product',
            name='brandspic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo brands'),
        ),
    ]
