# Generated by Django 3.1.4 on 2020-12-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='inDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='giriş tarihi'),
        ),
    ]
