# Generated by Django 3.1.4 on 2020-12-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_team_member_indate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productSpeciality',
            field=models.CharField(blank=True, choices=[('jaket', 'jaket'), ('pantolon', 'pantolon'), ('gömlek', 'gömlek'), ('mont', 'mont'), ('kölye', 'kölye'), ('halhal', 'halhal'), ('bilezik', 'bilezik'), ('küpe', 'küpe'), ('saat', 'saat'), ('etek', 'etek'), ('gözlük', 'gözlük')], max_length=100, null=True, verbose_name='ürün türü'),
        ),
    ]
