# Generated by Django 3.1.4 on 2020-12-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_product_productspeciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
