# Generated by Django 3.1.4 on 2020-12-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_delete_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='inDate',
        ),
    ]
