# Generated by Django 3.1.4 on 2020-12-15 08:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_remove_team_member_indate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='colorField',
            field=colorfield.fields.ColorField(blank=True, choices=[('red', 'red'), ('pink', 'pink'), ('orange', 'orange'), ('yellow', 'yellow'), ('purple', 'purple'), ('green', 'green'), ('blue', 'blue'), ('brown', 'brown'), ('black', 'black')], default=None, max_length=18, null=True, verbose_name='renk'),
        ),
    ]
