# Generated by Django 3.1.4 on 2020-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20201215_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productInformation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
