# Generated by Django 3.1.4 on 2020-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_product_productinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productInformation',
            field=models.TextField(blank=True, null=True, verbose_name='ürün bilgileri'),
        ),
    ]
