# Generated by Django 3.1.4 on 2020-12-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20201215_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprc',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='oldPrice'),
        ),
    ]
