# Generated by Django 3.1.4 on 2020-12-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_product_oldprc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='oldprc',
            new_name='oldprice',
        ),
    ]
