# Generated by Django 3.1.4 on 2020-12-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20201215_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('tl', '₺'), ('usd', '$'), ('euro', '€')], max_length=5, verbose_name='kur'),
        ),
    ]
