# Generated by Django 3.1.4 on 2020-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_auto_20201221_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('₺', 'TL'), ('$', 'USD'), ('€', 'EURO')], default='tl', max_length=5, verbose_name='kur'),
        ),
    ]
